title: CHERIoT Rust
description: >-
  Welcome to the CHERIoT Rust project, combining hardware-enforced memory safety with strong compile-time guarantees.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rust.cheriot.org"
github_username:  CHERIoT-Platform

collections:
  - people

# Build settings
theme: minima
#theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-scholar
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  toc_levels: "2,3"
  hard_wrap: false
  input: GFM


scholar:
  bibliography_template: bib
  style: ./_bibliography/cl-pubs
  bibliography: publications.bib
  sort_by: year
  order: descending


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
